title: "Toolskits Cloud Security Blog"
description: "Cloud security tips, tutorials, and tools."
baseurl: "/blog"
url: "https://toolskits.github.io"

# Use only supported plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
paginate: 5
paginate_path: "/page:num/"

# Markdown settings
markdown: kramdown
permalink: /:categories/:title/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
